apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/ip-allocated-from-pool: default-pool
  labels:
    app: ph2ifttt
  name: ph2ifttt
  namespace: ph2ifttt
spec:
  allocateLoadBalancerNodePorts: true
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    app: ph2ifttt
  sessionAffinity: None
  type: LoadBalancer

